import greenCordSet1 from "../Media/gs3.jpg";
import greenCordSet2 from "../Media/gs2.jpg";
import greenCordSet3 from "../Media/gs1.jpg";
import greenCordSet4 from "../Media/gs4.jpg";
import MCord1 from "../Media/mset1.jpg";
import MCord2 from "../Media/mset2.jpg";
import MCord3 from "../Media/mset3.jpg";
import MCord4 from "../Media/mset4.jpg";
import fiestaCord from "../Media/submenu-img.jpg";
import fiestaCord1 from "../Media/fiestaCord1.jpg";
import fiestaCord2 from "../Media/fiestaCord2.jpg";
import fiestaCord3 from "../Media/fiestaCord3.jpg";
import maroontop from "../Media/maroon top.webp";
import maroontop1 from "../Media/maroon-top1.webp";
import maroontop2 from "../Media/maroon-top2.webp";
import maroontop3 from "../Media/maroon-top3.webp";
import brownTop from "../Media/brown-top.webp";
import brownTop1 from "../Media/bt1.webp";
import brownTop2 from "../Media/bt2.webp";
import brownTop3 from "../Media/bt3.webp";
import checkDress from "../Media/checkDress.jpg";
import cd1 from "../Media/cd1.jpg";
import cd2 from "../Media/cd2.jpg";
import cd3 from "../Media/cd3.jpg";
import blackDress1 from "../Media/bd1.jpg";
import blackDress2 from "../Media/bd2.jpg";
import blackDress3 from "../Media/bd3.jpg";
import blackDress4 from "../Media/bd4.jpg";
import blueT1 from "../Media/blueTshirt.webp";
import blueT2 from "../Media/bluet1.webp";
import blueT3 from "../Media/blueT2.webp";
import blueT4 from "../Media/blueT3.webp";
import gs1 from "../Media/greensweatshirt1.avif"
import gs2 from "../Media/greenswaetshirt2.avif"
import gs3 from "../Media/greens3.avif"
import gs4 from "../Media/greens4.avif"
import sweatshirt1 from "../Media/lwuag_512.webp";
import sweatshirt2 from "../Media/iqjhn_512.webp";
import sweatshirt3 from "../Media/vmu1m_512.webp";
import sweatshirt4 from "../Media/z8xzc_512.webp";
import blueSweatshirt1 from "../Media/s1.webp";
import blueSweatshirt2 from "../Media/s2.webp";
import blueSweatshirt3 from "../Media/s3.webp";
import blueSweatshirt4 from "../Media/s4.webp";
import shawl1 from "../Media/free-1-gorgeous-women-woolen-stole-gladly-original-imagjxt9zbdrdncj.webp";
import shawl2 from "../Media/shawl2.webp";
import shawl3 from "../Media/shawl3.webp";
import shawl4 from "../Media/shawl4.webp";
import sh1 from "../Media/shl1.webp";
import sh2 from "../Media/shl2.webp";
import sh3 from "../Media/shl3.webp";
import sh4 from "../Media/shl4.webp";
import menshirt1 from "../Media/ekafw141.jpg";
import menshirt2 from "../Media/ekafw142.jpg";
import menshirt3 from "../Media/ekafw143.jpg";
import menshirt4 from "../Media/ekafw14b.jpg";
import pshirt1 from "../Media/askmsh00091purple1.jpg"
import pshirt2 from "../Media/askmsh00091purple2.jpg"
import pshirt3 from "../Media/askmsh00091purple3.jpg"
import pshirt4 from "../Media/askmsh00091purpleb.jpg"
import t1 from "../Media/t1.webp";
import t2 from "../Media/t2.webp";
import t3 from "../Media/t3.webp";
import t4 from "../Media/t4.webp";
import t5 from "../Media/t5.webp";
import t6 from "../Media/t6.webp";
import t7 from "../Media/t8.webp";
import t8 from "../Media/t9.webp";
import h1 from "../Media/h1.webp";
import h2 from "../Media/h2.webp";
import h3 from "../Media/h3.webp";
import h4 from "../Media/h4.webp";
import h5 from "../Media/h5.webp";
import h6 from "../Media/h6.webp";
import h7 from "../Media/h7.webp";
import h8 from "../Media/h8.webp";
import j1 from "../Media/j1.webp";
import j2 from "../Media/j2.webp";
import j3 from "../Media/j3.webp";
import j4 from "../Media/j4.webp";
import j5 from "../Media/J5.webp";
import j6 from "../Media/J6.webp";
import j7 from "../Media/J7.webp";
import j8 from "../Media/J8.webp";

export const westernData = [
    {
        id: "1",
        link3: "Indietoga Rayon Printed Co-ord Set for Women Western",
        image: `${greenCordSet1}`,
        category: "Co-ord Set",
        productType: "Indietoga Women's Plus Sizes Rayon Printed Co-ords Set for Women Western| (S to XL)",
        img1: `${greenCordSet2}`,
        img2: `${greenCordSet3}`,
        img3: `${greenCordSet4}`,
        price: 1499,
        pastPrice: 1750,
        taxes: "Inclusive of all taxes",
        about: "120+ bought in past month",
        ratings: "Based on 169 ratings",
        shipped: "Product will be shipped within 5 days.This product is eligible for return within 7 days",
        fabric: "Rayon",
        style: "Shirt",
        fitType: "Regular",
        care: "Machine Wash",
        sleeve: "3/4 Sleeves",
        origin: "Origin In INDIA",
        detail1: "Fabric : 100% High Class Printed Viscose Rayon Fabric, very soft and comfortable co-ord set",
        detail2: "Fit Type: Regular",
        detail3: "Style: Plus Size Green leaf printed rayon shirt has a button placket, spread collar, 3/4th sleeves and a subtle curved hemline. And paired with relaxed fit co-ord pants with elasticized waistband and two convenient pockets",
        detail4: "Occasion : Perfect for your daily wear, outdoor activity, dates and parties….And your occasion is perfect in spring, summer and fall."

    },
    {
        id: "2",
        link3: "Leriya Fashion Ethnic Co Ord Set",
        image: `${MCord1}`,
        category: "Co-ord Set",
        productType: "Leriya Fashion Ethnic Co Ord Set | Co Ord Set for Women | Night Dress for Women | Night Wear for Women | Payjama Set for Women | Women Two-Piece Outfits | Coord Sets",
        img1: `${MCord2}`,
        img2: `${MCord3}`,
        img3: `${MCord4}`,
        price: 2350,
        pastPrice: 4699,
        taxes: "Inclusive of all taxes",
        about: "120+ bought in past month",
        ratings: "1454 ratings",
        shipped: "Product will be shipped within 4 days.This product is eligible for return within 7 days",
        fabric: "Lycra Cotton",
        style: "Top-Bottom",
        care: "Hand-Wash Only",
        fitType: "Regular",
        sleeve: "3/4 Sleeves",
        origin: "Origin In INDIA",
        detail1: "Package includes : Pack of 1 Co Ord Set for Women Top and Bottom Set",
        detail2: "Sleeve and Fit Type : Full Sleeve Regular Fit Co-ord set for Women",
        detail3: "Collar Type : This Co-Ord Set for Women Has a V-Neck Design and Is a Perfect Option to Go for This Season, this Co-Ord for Women Comes with Regular Fit",
        detail4: "Material : Lycra Cotton Material is soft, silky feel, making it comfortable to wear against the skin, highly breathable, allowing air to pass through the fabric."

    },
    {
        id: "3",
        link3: "Fiesta Printed Co-ord Set",
        image: `${fiestaCord}`,
        category: "Co-ord Set",
        productType: "Fiesta Printed Co-ord Set",
        img1: `${fiestaCord1}`,
        img2: `${fiestaCord2}`,
        img3: `${fiestaCord3}`,
        price: 1599,
        pastPrice: 2000,
        taxes: "Inclusive of all taxes",
        about: "50+ bought in past month",
        ratings: "1100 ratings",
        shipped: "Product will be shipped within 4 days.This product is eligible for return within 7 days",
        fabric: "100% Cotton Blend",
        fitType: "Regular",
        style: "Multi Color",
        care: "Machine Wash",
        sleeve: "3/4 Sleeves",
        origin: "Origin In INDIA",
        detail1: "Fabric- Top: Cotton-Blend; Bottom: Cotton-Blend",
        detail2: "Color- Green",
        detail3: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
        detail4: "This top is sold with pant."

    },
    {
        id: "4",
        link3: "Casual Bell Sleeves Embroidered Women Maroon Top",
        image: `${maroontop}`,
        category: "Topwear",
        productType: "Casual Bell Sleeves Embroidered Women Maroon Top",
        img1: `${maroontop1}`,
        img2: `${maroontop2}`,
        img3: `${maroontop3}`,
        price: 499,
        pastPrice: 699,
        taxes: "Inclusive of all taxes",
        about: "50+ bought in past month",
        ratings: "1100 ratings",
        shipped: "Product will be shipped within 5 days.This product is eligible for return within 7 days",
        fabric: "Viscose Rayon",
        fitType: "Regular",
        style: "Maroon",
        care: "Machine Wash",
        sleeve: "Full Sleeves",
        origin: "Origin In INDIA",
        detail1: "Casual Bell Sleeves Embroidered Women Maroon Top",
        detail2: "Color- SILVEER WINE",
        detail3:"Bell Sleeves",
        detail4:  "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "5",
        link3: "Casual Regular Sleeves Printed Women Brown Top",
        image: `${brownTop}`,
        category: "Topwear",
        productType: "Casual Regular Sleeves Printed Women Brown Top",
        img1: `${brownTop1}`,
        img2: `${brownTop2}`,
        img3: `${brownTop3}`,
        price: 350,
        pastPrice: 499,
        taxes: "Inclusive of all taxes",
        about: "50+ bought in past month",
        ratings: "124 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Cotton Blend",
        style: "Brown",
        fitType: "Regular",
        care: "Machine Wash",
        sleeve: "Regular Sleeves",
        origin: "Origin In INDIA",
        detail1: "Embroidered Top",
        detail2: "Color-Brown",
        detail3: "Printed-Tunic",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "6",
        link3: "Navy Short Sleeve Round Neck Plaid Cotton Maxi Dress",
        image: `${checkDress}`,
        category: "Maxi Dress",
        productType: "Navy Short Sleeve Round Neck Plaid Cotton Maxi Dress",
        img1: `${cd1}`,
        img2: `${cd2}`,
        img3: `${cd3}`,
        price: 850,
        pastPrice: 999,
        taxes: "Inclusive of all taxes",
        about: "100+ bought in past month",
        ratings: "79 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Cotton",
        style: "Navy",
        fitType: "Regular",
        care: "Machine Wash",
        sleeve: "Half Sleeves",
        origin: "Origin In INDIA",
        detail1: "The Navy Plaid Tiered Dress is a sense of bliss that you should add to your wardrobe! This maxi dress features a round neck and short sleeve, also it has pockets! Wear to a blissful lunch date with your special someone or friends!",
        detail2: "Color-Navy",
        detail3: "Maxi-Dress",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "7",
        link3: "Black Round Neck Ruffle Long Sleeve Polka Dots Maxi Dress",
        image: `${blackDress1}`,
        category: "Maxi Dress",
        productType: "Black Round Neck Ruffle Long Sleeve Polka Dots Maxi Dress",
        img1: `${blackDress2}`,
        img2: `${blackDress3}`,
        img3: `${blackDress4}`,
        price: 1450,
        pastPrice: 1699,
        taxes: "Inclusive of all taxes",
        about: "200+ bought in past month",
        ratings: "159 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Cotton",
        style: "Black Polka Dot Dress",
        fitType: "Regular",
        care: "Machine Wash",
        sleeve: "Half Sleeves",
        origin: "Origin In INDIA",
        detail1: "This dress has all the details: round neckline, high waist, dainty, polka dots design!! Wear this dress from fall to spring and look like the new girl in town with all eyes on you.",
        detail2: "Color-Black",
        detail3: "Maxi-Dress",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "8",
        link3: "Women Printed Round Neck Pure Cotton Dark Blue T-Shirt",
        image: `${blueT1}`,
        category: "Maxi Dress",
        productType: "Women Printed Round Neck Pure Cotton Dark Blue T-Shirt",
        img1: `${blueT2}`,
        img2: `${blueT3}`,
        img3: `${blueT4}`,
        price: 269,
        pastPrice: 329,
        taxes: "Inclusive of all taxes",
        about: "80+ bought in past month",
        ratings: "129 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Pure Cotton",
        style: "T-shirt",
        fitType: "Regular",
        care: "Machine Wash",
        sleeve: "Short Sleeves",
        origin: "Origin In INDIA",
        detail1: "Navy Blue printed T-shirt, has a round neck, and short sleeves. This Roadster navy blue cotton tee will add versatility to your wardrobe. This navy blue piece can be teamed with cutoff denim shorts for a lazy weekend look or layered under a fitted jacket for a night out with friends.",
        detail2: "Color-Black",
        detail3: "Western Wear",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "9",
        link3: "Striped Crew-Neck Sweatshirt",
        image: `${gs1}`,
        category: "Sweatshirt & Hoddies",
        productType: "Striped Crew-Neck Sweatshirt",
        img1: `${gs2}`,
        img2: `${gs3}`,
        img3: `${gs4}`,
        price: 240,
        pastPrice: 599,
        taxes: "Inclusive of all taxes",
        about: "289+ bought in past month",
        ratings: "282 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "60% cotton, 40% polyester",
        style: "Sweatshirt",
        fitType: "Regular",
        care: "Machine Wash",
        sleeve: "Long Sleeves",
        origin: "Origin In INDIA",
        detail1: "Easy 10 days return and exchange. Return Policies may vary based on products and promotions. ",
        detail2: "Color-Striped white & pista green",
        detail3: "Western Wear",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "10",
        link3: "Woman Round Nack sweatshirt long sleeve",
        image: `${sweatshirt4}`,
        category: "Sweatshirt & Hoddies",
        productType: "Woman Round Nack sweatshirt long sleeve",
        img1: `${sweatshirt2}`,
        img2: `${sweatshirt3}`,
        img3: `${sweatshirt1}`,
        price: 310,
        pastPrice: 459,
        taxes: "Inclusive of all taxes",
        about: "56+ bought in past month",
        ratings: "162 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Wool",
        style: "Sweatshirt",
        fitType: "Regular",
        care: "Machine Wash",
        sleeve: "Long Sleeves",
        origin: "Origin In INDIA",
        detail1: "Women's fashion long sleeve round neck knitted drawstring hem sweatshirt, it has color block stripes that complement each other so well. ",
        detail2: "This casual sweaters is made of high quality fabric to keep you warm, durable and flatter your figure well.",
        detail3: "Cold weather clothing doesn't have to be basic. This color block sweater features warm, coordinating colors on a loose-fitting sweater.",
        detail4: "This fall winter loose knit sweaters designed in simple but generous. The bottom band drawstring top so you'll always have the perfect fit.",
    },
    {
        id: "11",
        link3: "Women Full Sleeve Striped Sweatshirt",
        image: `${blueSweatshirt1}`,
        category: "Sweatshirt & Hoddies",
        productType: "Women Full Sleeve Striped Sweatshirt",
        img1: `${blueSweatshirt2}`,
        img2: `${blueSweatshirt3}`,
        img3: `${blueSweatshirt4}`,
        price: 499,
        pastPrice: 859,
        taxes: "Inclusive of all taxes",
        about: "56+ bought in past month",
        ratings: "162 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Cotton-Blend",
        style: "Sweatshirt",
        fitType: "Regular",
        care: "Machine Wash",
        sleeve: "Long Sleeves",
        origin: "Origin In INDIA",
        detail1: "Easy 10 days return and exchange. Return Policies may vary based on products and promotions.",
        detail2: "This casual sweaters is made of high quality fabric to keep you warm, durable and flatter your figure well.",
        detail3: "Cold weather clothing doesn't have to be basic. This color block sweater features warm, coordinating colors on a loose-fitting sweater.",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "12",
        link3: "GLADLY Wool Printed Women Shawl  (Beige)",
        image: `${shawl1}`,
        category: "Shawl",
        productType: "Women Full Sleeve Striped Sweatshirt",
        img1: `${shawl2}`,
        img2: `${shawl3}`,
        img3: `${shawl4}`,
        price: 350,
        pastPrice: 599,
        taxes: "Inclusive of all taxes",
        about: "200+ bought in past month",
        ratings: "89 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Wool",
        style: "Shawl",
        fitType: "Regular",
        care: "Hand Wash",
        sleeve: "Printed",
        origin: "Origin In INDIA",
        detail1: "Easy 10 days return and exchange. Return Policies may vary based on products and promotions.",
        detail2: "Western Wear",
        detail3: "Color-Beige",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "13",
        link3: "CLASSIC SALES Wool Woven Women Shawl  (Brown)",
        image: `${sh1}`,
        category: "Shawl",
        productType: "CLASSIC SALES Wool Woven Women Shawl  (Brown)",
        img1: `${sh2}`,
        img2: `${sh3}`,
        img3: `${sh4}`,
        price: 424,
        pastPrice: 1429,
        taxes: "Inclusive of all taxes",
        about: "143+ bought in past month",
        ratings: "200+ ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Wool",
        style: "Shawl",
        fitType: "Regular",
        care: "Hand Wash",
        sleeve: "Printed",
        origin: "Origin In INDIA",
        detail1: "Easy 10 days return and exchange. Return Policies may vary based on products and promotions.",
        detail2: "Western Wear",
        detail3: "Color-Brown",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "14",
        link1: "Home",
        link2: "Shirt",
        link3: "Maroon Surkh Sanganeri Print Shirt",
        image: `${menshirt1}`,
        category: "Shirt",
        productType: "Maroon Surkh Sanganeri Print Shirt",
        img1: `${menshirt2}`,
        img2: `${menshirt3}`,
        img3: `${menshirt4}`,
        price: 1400,
        pastPrice: 1599,
        taxes: "Inclusive of all taxes",
        about: "89+ bought in past month",
        ratings: "359 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Pure Cotton",
        style: "Shirt",
        fitType: "Regular",
        care: "Machine Wash",
        sleeve: "Short Sleeves",
        origin: "Origin In INDIA",
        detail1: "Navy Blue printed T-shirt, has a round neck, and short sleeves. This Roadster navy blue cotton tee will add versatility to your wardrobe. This navy blue piece can be teamed with cutoff denim shorts for a lazy weekend look or layered under a fitted jacket for a night out with friends.",
        detail2: "Color-Black",
        detail3: "Western Wear",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "15",
        link3: "Cherry Multicolored Botanical Embroidery Shirt",
        image: `${pshirt1}`,
        category: "Shirt",
        productType: "Cherry Multicolored Botanical Embroidery Shirt",
        img1: `${pshirt2}`,
        img2: `${pshirt3}`,
        img3: `${pshirt4}`,
        price: 2500,
        pastPrice: 2999,
        taxes: "Inclusive of all taxes",
        about: "20+ bought in past month",
        ratings: "24 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Linen",
        style: "Shirt",
        fitType: "Regular",
        care: "Dry Clean Only",
        sleeve: "Long Sleeves",
        origin: "Origin In INDIA",
        detail1: "This cherry-colored shirt boasts intricate multicolored thread embroidery, depicting a delightful scene of trees and birds.",
        detail2: "Color-Purple",
        detail3: "Western Wear",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "16",
        link3: "Men Graphic Print Round Neck Pure Cotton Black T-Shirt",
        image: `${t1}`,
        category: "T-Shirt",
        productType: "Men Graphic Print Round Neck Pure Cotton Black T-Shirt",
        img1: `${t2}`,
        img2: `${t3}`,
        img3: `${t4}`,
        price: 275,
        pastPrice: 369,
        taxes: "Inclusive of all taxes",
        about: "50+ bought in past month",
        ratings: "43 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Pure Cotton",
        style: "T-Shirt",
        fitType: "Regular",
        care: "Machine Wash as per Tag",
        sleeve: "Half Sleeves",
        origin: "Origin In INDIA",
        detail1: "Easy 10 days return and exchange. Return Policies may vary based on products and promotions.",
        detail2: "Color-Black",
        detail3: "Round Neck T-Shirt",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "17",
        link3: "Men Printed Round Neck Organic Cotton Multicolor T-Shirt",
        image: `${t5}`,
        category: "T-Shirt",
        productType: "Men Printed Round Neck Organic Cotton Multicolor T-Shirt",
        img1: `${t6}`,
        img2: `${t7}`,
        img3: `${t8}`,
        price: 350,
        pastPrice: 699,
        taxes: "Inclusive of all taxes",
        about: "18+ bought in past month",
        ratings: "12 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Organic Cotton",
        style: "T-Shirt",
        fitType: "Regular",
        care: "Dry Clean Only",
        sleeve: "Half Sleeves",
        origin: "Origin In INDIA",
        detail1: "This bottle-green-colored t-shirt inhences the personality.",
        detail2: "Color-Green",
        detail3: "Round neck T-shirt",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "18",
        link3: "Men Full Sleeve Solid Hooded Sweatshirt",
        image: `${h1}`,
        category: "Sweatshirt",
        productType: "Men Full Sleeve Solid Hooded Sweatshirt",
        img1: `${h2}`,
        img2: `${h3}`,
        img3: `${h4}`,
        price: 449,
        pastPrice: 589,
        taxes: "Inclusive of all taxes",
        about: "48+ bought in past month",
        ratings: "39 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Cotton-Blend",
        style: "Hooded Neck",
        fitType: "Casual",
        care: "Machine Wash",
        sleeve: "Full Sleeves",
        origin: "Origin In INDIA",
        detail1: "Western Wear",
        detail2: "Color-Purple",
        detail3: "Purple Hooded Neck Sweatshirt",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "19",
        link3: "Men Full Sleeve Printed Sweatshirt",
        image: `${h5}`,
        category: "Sweatshirt",
        productType: "Men Full Sleeve Printed Sweatshirt",
        img1: `${h6}`,
        img2: `${h7}`,
        img3: `${h8}`,
        price: 550,
        pastPrice: 899,
        taxes: "Inclusive of all taxes",
        about: "90+ bought in past month",
        ratings: "56 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Cotton",
        style: "Sweatshirt",
        fitType: "Occasion",
        care: "Machine Wash",
        sleeve: "Full Sleeves",
        origin: "Origin In INDIA",
        detail1: "Western Wear",
        detail2: "Color-Brown",
        detail3: "Woolen Sweatshirt",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "20",
        link3: "Men Solid Bomber Jacket",
        image: `${j1}`,
        category: "Jacket",
        productType: "Men Solid Bomber Jacket",
        img1: `${j2}`,
        img2: `${j3}`,
        img3: `${j4}`,
        price: 998,
        pastPrice: 1499,
        taxes: "Inclusive of all taxes",
        about: "138+ bought in past month",
        ratings: "49 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Polyester",
        style: "Jacket",
        fitType: "Occasion",
        care: "Machine Wash as per tag",
        sleeve: "Full Sleeves",
        origin: "Origin In INDIA",
        detail1: "Western Wear",
        detail2: "Color-Green",
        detail3: "Bomber Jacket",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },
    {
        id: "21",
        link3: "Men Solid Bomber Jacket",
        image: `${j5}`,
        category: "Jacket",
        productType: "Men Solid Bomber Jacket",
        img1: `${j6}`,
        img2: `${j7}`,
        img3: `${j8}`,
        price: 799,
        pastPrice: 1199,
        taxes: "Inclusive of all taxes",
        about: "452+ bought in past month",
        ratings: "285 ratings",
        shipped: "Product will be shipped within 6 days.This product is eligible for return within 7 days",
        fabric: "Polyester",
        style: "Jacket",
        fitType: "Casual",
        care: "Machine Wash as per tag",
        sleeve: "Full Sleeves",
        origin: "Origin In INDIA",
        detail1: "Western Wear",
        detail2: "Color-Brown",
        detail3: "Bomber Jacket",
        detail4: "This product will be exclusively handcrafted for you, making the colour/texture/pattern slightly vary from the image shown, due to multiple artisan-led techniques and processes involved.",
    },

]